### PR TITLE
OOP for methods

### PR DESCRIPTION
**Pull request by AniketKumar2500**
I added certain new features for OOP and for now we can use it but only for calling methods from class.
Example:
```
class myclass:
 def say_hi:
  print 'Hi'

obj := object('myclass')
obj.say_hi(0)
```
* methods don't require param to be defined they are accessed as arg
* during calling any method we shall pass at least one argument for correct compilation and working.

And also solution for #232

### CODE REVIEW

**Comment by WithSJ** [comment]
Error while return something from method
**Csq**
```
class myclass:
 def say_hi:
  return 10

obj := object('myclass')
num := obj.say_hi(0)
print num
```

**Error**

```

hello.cpp: In function ‘int main(int, char**)’:
hello.cpp:12:49: error: invalid use of void expression
   12 | allocateVar("num","any",methodId("obj","say_hi")(i_val(0)));

```

**Review by WithSJ — APPROVED** [review]

**Comment by AniketKumar2500** [comment]
Now please check are you still getting error or not?

**Comment by usmanmusa1920** [comment]
Good feature and it awesome!

**Comment by WithSJ** [comment]
Fixing problems and adding cool stuff in the same place is a bit messy. It's like trying to do two things at once. 
Let's set up some more better rules and guide doc for contributing to Csq so that it's more organized and easy for everyone.

**Pull request merged**
