### PR TITLE
Update csq.py, build.sh

### PR DESCRIPTION
**Pull request by WithSJ**
we not need of make files now so i removed and for install csq i update build.sh

### CODE REVIEW

**Comment by WithSJ** [comment]
right now it's not working properly

**Comment by AniketKumar2500** [comment]
Nice step but you shou
ld fix some errors which i think are due to a conflict between python version.
Python3.10 includes a new statement type(match) but in the older ones it's not there.
In the below i recieved an error which i think is because python3<3.10 is used to run csq.
Screenshot_20230926_175114

**Comment by WithSJ** [comment]
> Nice step but you shou ld fix some errors which i think are due to a conflict between python version. Python3.10 includes a new statement type(match) but in the older ones it's not there. In the below i recieved an error which i think is because python3<3.10 is used to run csq. Screenshot_20230926_175114

yup... now test this in your device

**Comment by WithSJ** [comment]
please check your '.bashrc' file in your home directory, which is a hidden file, to see if the 'CSQ_INCLUDE' environment variable is set. If it's present, kindly remove it from the file and save the changes than run the 'build.sh' script again

i think i need to make uninstall.sh file

**Comment by AniketKumar2500** [comment]
Yes it would be easy to use then.

**Comment by AniketKumar2500** [comment]
But even after removing the error remains same.

**Pull request closed without merging**
