### PR TITLE
Change installation directory

### PR DESCRIPTION
**Pull request by gekkowrld**
Toy with #247

### CODE REVIEW

**Review by WithSJ — CHANGES_REQUESTED** [review]
Please include uninstall code and utilize functions 'install' and 'uninstall' in the script. Instead of removing all the code, make the necessary changes in the 'build.sh' file.

Please make changes to your code, and ensure not to use pyformatter as we are no longer using it at all.

**Comment by gekkowrld** [comment]
>  ensure not to use pyformatter as we are no longer using it at all

I already formatted with it, you can just ignore the changes to those files.

I made changes in `csq.py` and `build.sh`

**Comment by WithSJ** [comment]
while installing this error occur
```
chmod: cannot access '/opt/csq/src/csq.py': No such file or directory
ln: failed to create symbolic link '/usr/local/bin/csq': File exists
CSQ has been installed

```

**Comment by gekkowrld** [comment]
check pr #253 for update

**Pull request closed without merging**
